added insecure endpoints in OpAMP bridge configuration
Signed-off-by: Praful <holiodin@gmail.com>

diff --git a/tests/e2e-opampbridge/opampbridge/chainsaw-test.yaml b/tests/e2e-opampbridge/opampbridge/chainsaw-test.yaml
--- a/tests/e2e-opampbridge/opampbridge/chainsaw-test.yaml
+++ b/tests/e2e-opampbridge/opampbridge/chainsaw-test.yaml
@@ -137,3 +137,16 @@ spec:
                           receivers:
                             - jaeger
                             - otlp
+    - name: Ensure no errors in bridge logs
+      try:
+        - script:
+            content: |
+              #!/bin/bash
+              logs=$(kubectl logs -l app.kubernetes.io/name=test-opamp-bridge -n $NAMESPACE)
+              echo "$logs"
+              # Check for any "level":"error" or "bad handshake"
+              if echo "$logs" | grep -qiE "\"level\":\"error\"|bad handshake"; then
+                echo "Found an error in the logs!"
+                exit 1
+              fi
+              echo "No errors found."
